Retrofit resources
greenfox-zerda-raptors/peridot-coz-android pull request #12
Opened 2017-02-02 13:37 UTC by mozgaanna

nem tudom jo-e igy

2017-02-03 13:04 UTC, adamgyulavari approved these changes

2017-02-03 13:04 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/model/api/ApiService.java
> +    Call<Resource> getResource();
@mozgaanna this gives back a list of resources not a simple resource

2017-02-03 13:05 UTC, adamgyulavari requested changes

2017-02-03 13:05 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/model/api/ApiService.java
> +    Call<Resource> getResource();
so pls create a response model for that

2017-02-06 08:39 UTC, radaladar commented
pls create ResourceResponse class

2017-02-06 09:14 UTC, merged