Retrofit buildings
greenfox-zerda-raptors/peridot-coz-android pull request #13
Opened 2017-02-02 14:04 UTC by Phaedra144

Please check the retrofit extension, and please merge if fine.

Thanks, Szilvi

2017-02-02 15:14 UTC, adamgyulavari commented
@Phaedra144 resolve conflicts

2017-02-03 13:29 UTC, adamgyulavari requested changes

2017-02-03 13:29 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/model/api/ApiService.java
> +    Call<ArrayList<Building>> getBuildings(@Path("userId") int userId);
@Phaedra144 this is not what the API will give you back

2017-02-03 14:24 UTC, radaladar commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/model/api/ApiService.java
> +    Call<ArrayList<Building>> getBuildings(@Path("userId") int userId);
@adamgyulavari BuildingsResponse created on listview-buildings branch

2017-02-06 08:41 UTC, radaladar commented
pls resolve conflicts

2017-02-06 08:43 UTC, Phaedra144 commented
Done ;)

2017-02-06 09:02 UTC, merged