Refactor login and register after token based auth success
greenfox-zerda-raptors/peridot-coz-android pull request #34
Opened 2017-02-15 11:15 UTC by Phaedra144

2017-02-15 12:37 UTC, adamgyulavari requested changes

2017-02-15 12:37 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/LoginActivity.java
> +                        services.setApiService();
@PappBeata @Phaedra144 put this...

2017-02-15 12:37 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/LoginActivity.java
>          editor.apply();
...here

2017-02-15 12:37 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/LoginActivity.java
>          SharedPreferences loginData = getSharedPreferences("userInfo", Context.MODE_PRIVATE);
@Phaedra144 why the parameter?

2017-02-15 12:37 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/MainActivity.java
> +    String token = "";
@Phaedra144 why?

2017-02-15 12:37 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/provider/ApiProvider.java
> +    public ApiLoginService provideLoginApiManager() {return RestApiManager.getLoginApi();}
@Phaedra144 refactor these into one method with `if(MOCK)`...

2017-02-17 09:25 UTC, adamgyulavari approved these changes

2017-02-17 09:25 UTC, adamgyulavari commented
@Phaedra144 @PappBeata is this working, final?

2017-02-17 15:51 UTC, PappBeata commented
Unfortunately not yet. It creates the Services and the ApiLoginService and the ApiService, but only for Mock. The live version crashes.

2017-02-18 13:48 UTC, Phaedra144 commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/LoginActivity.java
> +                        services.setApiService();
I tried to replace "services" with "this", but android did not like it

2017-02-18 13:51 UTC, Phaedra144 commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/LoginActivity.java
>          editor.apply();
done :)

2017-02-18 13:52 UTC, Phaedra144 commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/LoginActivity.java
>          SharedPreferences loginData = getSharedPreferences("userInfo", Context.MODE_PRIVATE);
probably for some bad pattern, it's removed

2017-02-18 13:55 UTC, Phaedra144 commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/MainActivity.java
> +    String token = "";
for no reason, it!s been removed :)

2017-02-20 14:46 UTC, adamgyulavari reviewed
same question again? :)
@PappBeata @Phaedra144 final?

2017-02-22 11:36 UTC, Phaedra144 commented
Final!!! :)

2017-02-22 11:53 UTC, merged