Fix api endpoints
greenfox-zerda-raptors/peridot-coz-android pull request #38
Opened 2017-02-23 13:11 UTC by Phaedra144

2017-02-23 13:20 UTC, adamgyulavari requested changes

2017-02-23 13:20 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/api/MockService.java
> +                users.add(new User("Szilvi"));
@Phaedra144 move these to the constructor so it wont add them everytime this gets called

2017-02-23 13:20 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/api/MockService.java
> +                Response<Troop> r = Response.success(new Troop(10, 2, 1));
@Phaedra144 use the `troop` passed as param, update it and send that back

2017-02-23 16:25 UTC, Phaedra144 commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/api/MockService.java
> +                users.add(new User("Szilvi"));
Done :)

2017-02-23 16:52 UTC, Phaedra144 commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/api/MockService.java
> +                Response<Troop> r = Response.success(new Troop(10, 2, 1));
I hope it's done :D

2017-02-23 16:53 UTC, Phaedra144 commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/api/MockService.java
> +                Response<Troop> r = Response.success(new Troop(10, 2, 1));
committed corrections

2017-02-24 09:40 UTC, adamgyulavari approved these changes

2017-02-24 09:40 UTC, merged