Navigation drawer from app bar
greenfox-zerda-raptors/peridot-coz-android pull request #5
Opened 2017-01-30 13:25 UTC by PappBeata

We have put the pieces (toolbar and drawer parts) in place. Now our structure follows the structure of an android studio standrard activity with navigation bar.

2017-01-30 14:01 UTC, adamgyulavari requested changes

2017-01-30 14:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/fragment/FirstFragment.java
> +        contentView = inflater.inflate(R.layout.first_layout, container, false);
@PappBeata dont need to store the contentView as class variable, have it declared in the method

2017-01-30 14:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/fragment/SecondFragment.java
> +        contentView = inflater.inflate(R.layout.second_layout, container, false);
@PappBeata same in english

2017-01-30 14:09 UTC, PappBeata commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/fragment/FirstFragment.java
> +        contentView = inflater.inflate(R.layout.first_layout, container, false);
Done

2017-01-30 14:09 UTC, PappBeata commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/fragment/SecondFragment.java
> +        contentView = inflater.inflate(R.layout.second_layout, container, false);
Done

2017-01-30 14:29 UTC, adamgyulavari approved these changes

2017-01-30 14:30 UTC, adamgyulavari commented
@PappBeata resolve conflicts :)

2017-01-31 08:52 UTC, PappBeata commented
Should be ok. Sorry, I haven't press on commit after marking as solved...

2017-01-31 09:10 UTC, adamgyulavari requested changes

2017-01-31 09:10 UTC, adamgyulavari commented on app/src/main/res/drawable-v21/ic_menu_manage.xml
> +</vector>
new line @PappBeata

2017-01-31 09:10 UTC, adamgyulavari commented on app/src/main/res/layout/first_layout.xml
> +</RelativeLayout>
new line @PappBeata

2017-01-31 09:10 UTC, adamgyulavari commented on app/src/main/res/layout/second_layout.xml
> +</RelativeLayout>
new line @PappBeata

2017-01-31 09:10 UTC, adamgyulavari commented on app/src/main/res/drawable/side_nav_bar.xml
> +</shape>
new line @PappBeata

2017-01-31 09:57 UTC, PappBeata commented
Dependency change of master left unchanged. (-Lombok +android.support.design)

2017-01-31 09:57 UTC, PappBeata commented on app/src/main/res/drawable/side_nav_bar.xml
> +</shape>
New lines added.

2017-01-31 09:57 UTC, PappBeata commented on app/src/main/res/layout/second_layout.xml
> +</RelativeLayout>
Addded

2017-01-31 09:57 UTC, PappBeata commented on app/src/main/res/layout/first_layout.xml
> +</RelativeLayout>
Added

2017-01-31 09:58 UTC, PappBeata commented on app/src/main/res/drawable-v21/ic_menu_manage.xml
> +</vector>
Added.

2017-01-31 12:20 UTC, adamgyulavari approved these changes

2017-01-31 12:20 UTC, merged