Response branch
greenfox-zerda-raptors/peridot-coz-android pull request #7
Opened 2017-01-31 14:40 UTC by mozgaanna

2017-02-01 13:46 UTC, adamgyulavari requested changes

2017-02-01 13:46 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/model/response/RegResponse.java
> +}
@mozgaanna if this is the same in the specs (my bad), then don't create the same object, just use the same for both eg. `LoginAndRegResponse`

2017-02-01 14:43 UTC, radaladar commented
@adamgyulavari loginandregisterresponse fixd

2017-02-02 10:04 UTC, radaladar commented
@adamgyulavari conflicts solved

2017-02-02 10:39 UTC, adamgyulavari approved these changes

2017-02-02 10:39 UTC, merged