KingdomOverviewFragment with Logout button as the main screen
greenfox-zerda-raptors/peridot-coz-android pull request #8
Opened 2017-01-31 16:20 UTC by mozgaanna

FragmentManager replaced with FragmentTransaction,
app.Fragment import replaced with support.v4.app.Fragment.

2017-02-01 13:51 UTC, adamgyulavari requested changes

2017-02-01 13:51 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/MainActivity.java
> +        fragmentTransaction.commit();
@radaladar `FragmentTransaction` is chainable, you don't need to store it in a variable, you can just call the methods on the previous ones

2017-02-01 13:51 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/MainActivity.java
> +        SharedPreferences preferences = this.getSharedPreferences("userInfo", Context.MODE_PRIVATE);
@radaladar `this` is not needed

2017-02-01 13:51 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/MainActivity.java
> +        this.startActivity(loginIntent);
@radaladar `this` is not needed again, and also you can just instantiate the intent as the parameter

2017-02-01 13:51 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/peridot/peridot_coz_android/activity/MainActivity.java
> +            fragmentTransaction.commit();
@radaladar chaining here as well

2017-02-01 14:27 UTC, radaladar commented
@adamgyulavari requested changes done

2017-02-02 10:44 UTC, adamgyulavari approved these changes

2017-02-02 10:44 UTC, merged